version: "3"
services:
    exporter:
        image: netbrainit/anynodeexporter:latest
        ports:
            - "9910:80"
        restart: always
        environment:
            - "ae_Anynode__User=anadmin"
            - "ae_Anynode__Password=secret"
            - "ae_Anynode__Url=https://192.168.178.10"
            - "TZ=Europe/Berlin"
